### ISSUE TITLE
Support for lists (ul/ol)

### ISSUE THREAD

**Issue by joenas** [Sorunome/slack-markdown#18]
Hey!

Great library, glad it seems to be supported as other solutions I've found are rather old. Just one question though, it doesn't seem to support lists at all, neither slack formatted nor regular markdown. Is there any particular reason for that?

**Comment by Sorunome** [comment]
Does slackdown even support lists? Keep in mind that what you send in slack web and whatnot is converted to undocumented slack blocks, which are then used for rendering. If you can help by verifying that it is actually part of slackdown, e.g. by sending a message from a bot, then soru could get on to implement it.

As for the undocumented slack blocks, which bots and whatnot can actually send! Soru made a package called `matrix-slack-parser` (also on npm, repository [here](https://gitlab.com/mx-puppet/slack/matrix-slack-parser)) which converts [matrix messages](https://matrix.org) to slack messages and vice versa, including blocks and whatnot. As the API is geared towards matrix, it might be a bit funky to use for an arbitrary project, but it should definitely still be possible! That project also depends on this one, in case of the absence of blocks or there are some blocks which require slackdown for some of the parameters.

Soru hops that this wall of text helps!

**Comment by joenas** [comment]
No, you're right - lists are [not supported](https://api.slack.com/reference/surfaces/formatting#block-formatting) 🙁 

My use case is displaying saved Slack messages on web so a bit different from bot/app messages. With the WYSIWYG editor you can create lists as a user so I was hoping this lib would handle those too hehe. 
I guess maybe I could pipe the input through a regular markdown-to-html first.. 😬

**Comment by joenas** [comment]
Big fan of Matrix btw so cool to see you're active there!

**Comment by Sorunome** [comment]
why not pipe through matrix-slack-parser instead, then, as it properly does lists, *and* you get html as a result ^^

20. 5. 2022 10:10:39 Jon Neverland ***@***.***>:

**Comment by Sorunome** [comment]
> With the WYSIWYG editor you can create lists as a user so I was hoping this lib would handle those too hehe.

That's exactly the undocumented blocks that matrix-slack-parser handles which soru mentioned. Soru spent quite some time reverse-engineering slack for that, even going as far as to looking at their minified source code to see if she had missed any formatting blocks ^^

**Comment by Sorunome** [comment]
like, if there are blocks present then the plain body is totally ignored anyways, so if you only go by the slackdown you could construct a message which displays differently in your application and on slack.
