### ISSUE TITLE
Support tag a with target '_blank'

### ISSUE THREAD

**Issue by donglnp** [Sorunome/slack-markdown#22]

**Comment by donglnp** [comment]
Every one!

Great library, glad it seems to be supported as the other solutions I found is quite old. However, only one question, it doesn't seem to support opening a new tab if it's a link, can you support open a new tag with tag <a />

**Comment by Sorunome** [comment]
Done and published! https://github.com/Sorunome/slack-markdown/commits/master

**Comment by donglnp** [comment]
@Sorunome  Thank you very much
